version: 2

jobs:
  build:
    docker:
      - image: node:10.15
    working_directory: ~/dist
    steps:
      - checkout
      - run:
          name: NPM token configuration
          command: echo $NPM_TOKEN > ~/.npmrc
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Building NPM
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  release:
    docker:
      - image: node:10.15
    working_directory: ~/dist
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          name: NPM token configuration
          command: echo $NPM_TOKEN > ~/.npmrc
      - run:
          name: Releasing NPM
          command: npm run build:release
workflows:
  version: 2
  build-release:
    jobs:
      - build:
          context: datahub-prod
          filters:
            branches:
              only:
                - develop
                - master
                - /feature\/.*/
            tags:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
      - release:
          context: datahub-prod
          requires:
            - hold
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
