openapi: 3.0.1
info:
  title: SkyAPI
  version: 2.0.0
  description: Management layer on top of AWS and Processing Pipeline
  termsOfService: https://skycatch.com/terms/
  contact:
    url: https://skycatch.com/contacts/
    email: api@skycatch.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  url: https://docs.skycatch.com/v2.0.0/reference
  description: SkyAPI Documentation
servers:
  - url: https://{environment}.skycatch.com/v2
    variables:
      environment:
        description: The environment you are building the API for
        enum:
          - api         # prod
          - staging-api # stage
        default: api
  - url: https://{tenant}.auth0.com/oauth/token
    variables:
      tenant:
        description: The Auth0 tenant
        enum:
          - skycatch-development
          - skycatch-staging
          - skycatch-production
        default: skycatch-development
components:
  securitySchemes:
    auth0: # arbitrary name
      name: auth0
      type: oauth2
      description: Used by organization apps
      flows:
        clientCredentials: # authorizationCode, implicit, password or clientCredentials)
          tokenUrl: https://{tenant}.auth0.com/oauth/token
          scopes: {}
          # scopes:
          #   read_pets: read your pets
          #   write_pets: modify pets in your account
paths:
  /ccrs/localization:
    post:
      $ref: '../node_modules/@skycatch/skyapi-ccrs-localization-post/spec/lambda.yml'
  /credentials/filemanager:
    post:
      $ref: '../node_modules/@skycatch/skyapi-credentials-filemanager-post/spec/lambda.yml'
  /datasets:
    post:
      $ref: '../node_modules/@skycatch/skyapi-datasets-post/spec/lambda.yml'
  /datasets/{uuid}:
    get:
      $ref: '../node_modules/@skycatch/skyapi-datasets-get/spec/lambda.yml'
  /datasets/{uuid}/processes:
    get:
      $ref: '../node_modules/@skycatch/skyapi-datasets-processes-list/spec/lambda.yml'
    post:
      $ref: '../node_modules/@skycatch/skyapi-datasets-processes-post/spec/lambda.yml'
  /designfiles/{uuid}:
    get:
      $ref: '../node_modules/@skycatch/skyapi-designfiles-get/spec/lambda.yml'
  /geoids:
    get:
      $ref: '../node_modules/@skycatch/skyapi-geoids-list/spec/lambda.yml'
  /geoids/{id}/height:
    get:
      $ref: '../node_modules/@skycatch/skyapi-geoids-height-get/spec/lambda.yml'
  /processes/{uuid}/result:
    get:
      $ref: '../node_modules/@skycatch/skyapi-processing-result-get/spec/lambda.yml'
  /projections:
    get:
      $ref: '../node_modules/@skycatch/skyapi-projections-get/spec/lambda.yml'
