openapi: 3.0.1
info:
  title: SkyAPI
  version: 2.0.0
  description: Management layer on top of AWS and Processing Pipeline
  termsOfService: https://skycatch.com/terms/
  contact:
    url: https://skycatch.com/contacts/
    email: api@skycatch.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  url: https://docs.skycatch.com/v2.0.0/reference
  description: SkyAPI Documentation
servers:
  - url: https://api.skycatch.com/v2
  - url: https://staging-gemba.skycatch.com/v2
paths:
  /datasets:
    post:
      $ref: '../node_modules/@skycatch/skyapi-datasets-post/spec/lambda.yml'
  /datasets/{uuid}/processes:
    post:
      $ref: '../node_modules/@skycatch/skyapi-datasets-processes-post/spec/lambda.yml'
